import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/serviceprovidereditprofilepage">
            Serviceprovidereditprofilepage
          </Link>
        </li>
        <li>
          <Link to="/serviceprovidersideprofile">
            ServiceProviderSideProfile
          </Link>
        </li>
        <li>
          <Link to="/notificationpage">NotificationPage</Link>
        </li>
        <li>
          <Link to="/servicelist">Servicelist</Link>
        </li>
        <li>
          <Link to="/serviceproviderhomepage">ServiceProviderHomePage</Link>
        </li>
        <li>
          <Link to="/bookingstatuschangingdialog">
            BookingStatusChangingDialog
          </Link>
        </li>
        <li>
          <Link to="/bookingsuccessfulpage">BookingSuccessfulpage</Link>
        </li>
        <li>
          <Link to="/userprofile">Userprofile</Link>
        </li>
        <li>
          <Link to="/bookingpage">BookingPage</Link>
        </li>
        <li>
          <Link to="/searchresult">Searchresult</Link>
        </li>
        <li>
          <Link to="/bookingdetails">Bookingdetails</Link>
        </li>
        <li>
          <Link to="/editprofile">Editprofile</Link>
        </li>
        <li>
          <Link to="/helppage">Helppage</Link>
        </li>
        <li>
          <Link to="/serviceproviderprofile">ServiceProviderProfile</Link>
        </li>
        <li>
          <Link to="/bookingform">Bookingform</Link>
        </li>
        <li>
          <Link to="/signuppage">Signuppage</Link>
        </li>
        <li>
          <Link to="/loginpage">Loginpage</Link>
        </li>
        <li>
          <Link to="/forgotpassword">Forgotpassword</Link>
        </li>
        <li>
          <Link to="/cancelbooking">Cancelbooking</Link>
        </li>
        <li>
          <Link to="/reschedulebooking">Reschedulebooking</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
